### ISSUE TITLE
How to get styling to work ?

### ISSUE THREAD

**Issue by KelvinSan** [json-schema-form-element/jsfe#10]
I can get the form to generate but styling does not load.

**Comment by JulianCataldo** [comment]
JSFE core is headless, all additionnal UI libs are implementation demos for you to copy, extend, modify…

For example, MD-ui is not officially maintained anymore. It's too much work (and not very interesting for me) to support every CSS implementations, which is all chaos in the current state of the front-end.

I recommend to copy Shoelace or System, and hack on it ;)
